apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: traceId
          datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          urlDisplayLabel: "View Trace"
          url: "$${__value.raw}"
