auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-10-24
    store: tsdb
    object_store: ${LOKI_STORAGE_BACKEND}
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
  aws:
    region: ${LOKI_AWS_REGION}
    endpoint: ${LOKI_AWS_ENDPOINT}
    bucketnames: ${LOKI_AWS_BUCKET}
    access_key_id: ${LOKI_AWS_ACCESS_KEY_ID}
    secret_access_key: ${LOKI_AWS_SECRET_ACCESS_KEY}
    # s3forcepathstyle: true
    insecure: true
