multitenancy_enabled: false

server:
  http_listen_port: 8080

blocks_storage:
  backend: ${MIMIR_STORAGE_BACKEND}
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  tsdb:
    dir: /tmp/mimir/tsdb
  filesystem:
    dir: /tmp/mimir/data/tsdb
  s3:
    region: ${MIMIR_AWS_REGION}
    endpoint: ${MIMIR_AWS_ENDPOINT}
    bucket_name: ${MIMIR_AWS_BUCKET}
    access_key_id: ${MIMIR_AWS_ACCESS_KEY_ID}
    secret_access_key: ${MIMIR_AWS_SECRET_ACCESS_KEY}
    insecure: ${INSECURE_CONNECTION}

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/alerts

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

store_gateway:
  sharding_ring:
    replication_factor: 1
