server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  trace_idle_period: 10m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: ${TEMPO_STORAGE_BACKEND}
    local:
      path: /tmp/tempo/blocks
    s3:
      region: ${TEMPO_AWS_REGION}
      endpoint: ${TEMPO_AWS_ENDPOINT}
      bucket: ${TEMPO_AWS_BUCKET}
      access_key: ${TEMPO_AWS_ACCESS_KEY_ID}
      secret_key: ${TEMPO_AWS_SECRET_ACCESS_KEY}
      insecure: ${INSECURE_CONNECTION}
    wal:
      path: /tmp/tempo/wal

metrics_generator:
  processor:
    span_metrics:
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
    service_graphs:
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
    local_blocks:
        flush_to_storage: true
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:8080/api/v1/push
        send_exemplars: true
  traces_storage:
    path: /tmp/tempo/generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both
